config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'messages/index'
  get 'conversations/index'
  resources :items
  resources :news
  get 'home/index'
  root 'home#index'
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  resources :users

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  get 'home/search', to: 'home#search', as: 'search'
  post 'set_locale', to: 'home#set_locale'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @items = Item.all.order(updated_at: :desc).page(params[:page]).per(10)
    @search = params["search"]
    if @search.present?
      @items = Item.where('title LIKE ?', "%#{@search}").order(updated_at: :desc).page(params[:page]).per(10)
    end
    @sort = params[:sort]
    if @sort.present?
      var = @sort[0].to_i
      case var
      when 1
        @items= Item.all.order(updated_at: :asc).page(params[:page]).per(10)
      when 2
        @items= Item.all.order(updated_at: :desc).page(params[:page]).per(10)
      when 3
        @items= Item.all.order(price: :asc).page(params[:page]).per(10)
      when 4
        @items= Item.all.order(price: :desc).page(params[:page]).per(10)
      else
        @items= Item.all.order(updated_at: :desc).page(params[:page]).per(10)
      end
    end
  end

  def search
    @items = Item.search(search_params).order(updated_at: :desc).page(params[:page]).per(10)
    render 'home/index'
  end

  def set_locale
    I18n.default_locale = params[:locale]
    redirect_back(fallback_location: root_path)
  end

  private

  def item_params
    params.require(:search).permit(:name)
  end

  def item_sort_params
    params.require(:sort).permit(:updated_at, :price)
  end

  def search_params
    params.permit(:city_id, :category, :price_from, :price_to, :condition, :image_file_size)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.haml
.row.border-simple
  .col-10.mt-2
    %p= "#{t(:ad_total)} #{Item.count}"
    .row.mb-2
      = form_tag(root_path, method: :get) do
        .col.item-category= t(:all)
      .col.text-center.item-category= t(:property)
      .col.text-center.item-category= t(:auto)
      .col.text-center.item-category= t(:technics)
      .col.text-center.item-category= t(:clothes)
      .col.text-center.item-category= t(:sports)
      .col.text-center.item-category= t(:animals)
      .col.text-center.item-category= t(:work)
      .col.text-center.item-category= t(:service)
      .col.text-center.item-category= t(:other)
  .col-2.mt-2
    .row
      .col-12
        = form_tag(root_path, method: :get) do
          .form-group.text-right= select_tag :sort, options_for_select([[t(:sort_ads_by), 0], [t(:sort_oldest), 1], [t(:sort_newest), 2],
          [t(:sort_cheapest), 3], [t(:sort_expensive), 4]]), onchange: "this.form.submit();", class: 'form-control'
          = submit_tag :sort_by_submit, style: 'display: none;', id: 'sort_submit'
.row
  .col-10
    - @items.each do |item|
      .col-12
        = link_to item_path(item) do
          .adv.border-body.mt-2
            .row
              .col-3= image_tag item.image.url(:medium), class: 'img-fluid adv-img-index'
              .col-7.border-left
                .item-title= item.title
                .item-category= item.category
                .item-description= item.description
                %br
                .item-city= item.city.name
              .col-2
                .item-price.text-right= "#{item.price} p."
                %br
                %br
                %br
                .item-updated.text-right= item.updated_at.to_formatted_s(:short)
  .col-2.mt-2.border-left.border-top.bg-light
    = form_tag(search_path, method: :get, html: { class: 'form-inline' }) do
      .row.form-group.mt-2
        .col-12
          = label_tag t(:city_id)
        .col-12
          = select_tag :city_id, options_for_select([[t(:city_brest), 1], [t(:city_vitebsk), 2], [t(:city_gomel), 3], [t(:city_grodno), 4], [t(:city_minsk_area), 5], [t(:city_mogilev), 6], [t(:city_minsk), 7]].prepend([t(:all), nil])), class: 'form-control-sm search-controls'
      .row.form-group.mt-2
        .col-12
          = label_tag t(:category)
        .col-12
          = select_tag :category, options_for_select(Item.categories.map{ |key, value| [key, value] }.prepend([t(:all), nil ])), class: 'form-control-sm search-controls'
      .row.form-group.mt-2
        .col-12
          = label_tag t(:price)
        .col-6
          = text_field_tag :price_from, nil, placeholder: t(:from), class: 'form-control search-controls'
        .col-6
          = text_field_tag :price_to, nil, placeholder: t(:to), class: 'form-control search-controls'
      .row.form-group.mt-2
        .col-12
          = label_tag t(:condition)
        .col-12
          = radio_button_tag :condition, "", true
          = label_tag t(:any)
        .col-12
          = radio_button_tag :condition, t(:new)
          = label_tag t(:new)
        .col-12
          = radio_button_tag :condition, t(:not_new)
          = label_tag t(:not_new)
      .row.form-group.mt-2
        .col-6
          = label_tag t(:only_with_photo)
        .col-6
          = check_box_tag :image_file_size, checked_value = true, unchecked_value = nil, checked: true
      .row.form-group.mt-2
        .col-12
          = submit_tag t(:results), class: 'btn btn-success btn-block'
.row.mt-2
  .col
  .col
    = paginate @items
  .col
.row
  .col
  .col
    = page_entries_info @items
  .col