config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'messages/index'
  get 'conversations/index'
  resources :items
  resources :news
  get 'home/index'
  root 'home#index'
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  resources :users

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  get 'home/search', to: 'home#search', as: 'search'
  post 'set_locale', to: 'home#set_locale'
end

app/models/news.rb
class News < ApplicationRecord
  belongs_to :user

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :set_news, only: [:show, :edit, :update, :destroy]

  # GET /news
  # GET /news.json
  def index
    @news = News.all
  end

  # GET /news/1
  # GET /news/1.json
  def show
  end

  # GET /news/new
  def new
    @news = News.new
  end

  # GET /news/1/edit
  def edit
  end

  # POST /news
  # POST /news.json
  def create
    @news = News.new(news_params)

    respond_to do |format|
      if @news.save
        format.html { redirect_to @news, notice: 'News was successfully created.' }
        format.json { render :show, status: :created, location: @news }
      else
        format.html { render :new }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news/1
  # PATCH/PUT /news/1.json
  def update
    respond_to do |format|
      if @news.update(news_params)
        format.html { redirect_to @news, notice: 'News was successfully updated.' }
        format.json { render :show, status: :ok, location: @news }
      else
        format.html { render :edit }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    @news.destroy
    respond_to do |format|
      format.html { redirect_to news_index_url, notice: 'News was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news
      @news = News.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def news_params
      params.require(:news).permit(:title, :description, :user_id, :published)
    end
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/news/_form.html.haml
= form_for @news do |f|
  - if @news.errors.any?
    #error_explanation
      %h2= "#{pluralize(@news.errors.count, "error")} prohibited this news from being saved:"
      %ul
        - @news.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :description
    = f.text_field :description
  .field
    = f.label :user
    = f.text_field :user
  .field
    = f.label :published
    = f.check_box :published
  .actions
    = f.submit 'Save'

app/views/news/edit.html.haml
%h1 Editing news

= render 'form'

= link_to 'Show', @news
\|
= link_to 'Back', news_index_path

app/views/news/index.html.haml
%h1 Listing news

%table
  %thead
    %tr
      %th Title
      %th Description
      %th User
      %th Published
      %th
      %th
      %th

  %tbody
    - @news.each do |news|
      %tr
        %td= news.title
        %td= news.description
        %td= news.user
        %td= news.published
        %td= link_to 'Show', news
        %td= link_to 'Edit', edit_news_path(news)
        %td= link_to 'Destroy', news, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New News', new_news_path

app/views/news/new.html.haml
%h1 New news

= render 'form'

= link_to 'Back', news_index_path

app/views/news/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @news.title
%p
  %b Description:
  = @news.description
%p
  %b User:
  = @news.user
%p
  %b Published:
  = @news.published

= link_to 'Edit', edit_news_path(@news)
\|
= link_to 'Back', news_index_path