config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'messages/index'
  get 'conversations/index'
  resources :items
  resources :news
  get 'home/index'
  root 'home#index'
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  resources :users

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  get 'home/search', to: 'home#search', as: 'search'
  post 'set_locale', to: 'home#set_locale'
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  belongs_to :city

  validates :price, :title, presence: true

  enum category: { Property: 0, Auto: 1, Technics: 2, Clothes: 3, Sports: 4, Animals: 5, Work: 6, Service: 7, Other: 8 }
  has_attached_file :image,
                    styles: { medium: "300x300>", index: "200x125>", thumb: "100x100>", small: "40x40" },
                    default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  def self.search(params)
    params.delete_if { |_key, value| value.empty? }
    if params[:price_from].present? && params[:price_to].present?
      params[:price] = params[:price_from]..params[:price_to]
      params.delete(:price_from)
      params.delete(:price_to)
    elsif params[:price_from].present? && params[:price_to].blank?
      params[:price] = params[:price_from].to_i..9999999999999
      params.delete(:price_from)
      params.delete(:price_to)
    elsif params[:price_from].blank? && params[:price_to].blank?
    else
      params[:price] = 0..params[:price_to].to_i
      params.delete(:price_from)
      params.delete(:price_to)
    end

    if params[:image_file_size].present?
      params[:image_file_size] = 1..99999999
      where(params)
    else
      where(params)
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
    authorize @items
  end

  # GET /items/1
  # GET /items/1.json
  def show
    authorize @item
  end

  # GET /items/new
  def new
    @item = Item.new
    authorize @item
  end

  # GET /items/1/edit
  def edit
    authorize @item
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)
    authorize @item

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    authorize @item
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    authorize @item
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:title, :description, :category, :price, :manufacturer, :condition, :user_id,
                                   :published, :image, :city_id)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.haml
= form_for @item, html: { multipart: true } do |f|
  - if @item.errors.any?
    #error_explanation
      %h2= "#{pluralize(@item.errors.count, "error")} prohibited this item from being saved:"
      %ul
        - @item.errors.full_messages.each do |message|
          %li= message

  .form-group.row
    .col-2
      = f.label t(:title)
    .col-10
      = f.text_field :title, class: 'form-control'
  .form-group.mt-4.row
    .col-2
      = f.label t(:category)
    .col-10
      = f.select :category, Item.categories.keys, class: 'form-control', id: 'category'
  .form-group.row
    .col-2
      = f.label t(:description)
    .col-10
      = f.text_area :description, class: 'form-control'
  .form-group.row
    .col-2
      = f.label t(:manufacturer)
    .col-10
      = f.text_field :manufacturer, class: 'form-control'
  .form-group.row
    .col-2
      = f.label t(:condition)
    .col-10
      = f.select :condition, options_for_select([[t(:new), 'New'], [t(:not_new), 'Not new']].prepend(['-', nil])), class: 'form-control'
  .form-group.row
    .col-2
      = f.label t(:image)
    .col-10.image-form
      = f.file_field :image
  .form-group.row
    .col-2
      = f.label t(:city_id)
    .col-10
      = f.select :city_id, [[t(:city_brest), 1], [t(:city_vitebsk), 2], [t(:city_gomel), 3], [t(:city_grodno), 4], [t(:city_minsk_area), 5], [t(:city_mogilev), 6], [t(:city_minsk), 7], [t(:none), 8]], class: 'form-control'
  .form-group.row
    .col-2
      = f.label t(:price)
    .col-10
      = f.number_field :price, class: 'form-control'
  .field
    = f.hidden_field :user_id, value: current_user.id
  .field
    = f.hidden_field :published, value: true

  -#.field
  -#  = f.label :pictures, class: 'control-label'
  -#  = file_field_tag "images[]", type: :file, multipart: true
  .form-group
    = f.submit t(:save), class: 'btn btn-success'

app/views/items/edit.html.haml
.container
  .row.mt-4
    .col-12
      %h2.text-center=t(:item_edit)
      .col-12.border-body
        = render 'form'

        = link_to t(:show), @item, class: 'btn btn-primary'
        \|
        = link_to t(:back), items_path, class: 'btn btn-secondary'

app/views/items/index.html.haml
%h1 Listing items

%table
  %thead
    %tr
      %th Title
      %th Description
      %th Category
      %th Price
      %th Manufacturer
      %th Condition
      %th User
      %th Published
      %th
      %th
      %th

  %tbody
    - @items.each do |item|
      %tr
        %td= item.title
        %td= item.description
        %td= item.category
        %td= item.price
        %td= item.manufacturer
        %td= item.condition
        %td= item.user
        %td= item.published
        %td= link_to 'Show', item
        %td= link_to 'Edit', edit_item_path(item)
        %td= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Item', new_item_path

app/views/items/new.html.haml
.container
  .row.mt-4
    .col-12
      %h2.text-center=t(:item_new)
      .col-12.border-body
        = render 'form'

        = link_to t(:back), items_path, class: 'btn btn-secondary'

app/views/items/show.html.haml
%p#notice= notice
.container-fluid.border-body
  .row
    .col-8
      = image_tag @item.image.url(:original), class: 'item-image-big img-fluid'
    .col-4.border-left
      %h4.font-weight-bold= @item.title
      %h5.text-sm= @item.city.name
      %br
      %h4.font-weight-bold= "#{@item.price} p."
      = link_to t(:message_owner), root_path, class: 'btn btn-success btn-block'
      .contacts-window.mt-2.border-body.text-center
        %h5= @item.user.first_phone
        %h5= @item.user.second_phone
      .owner-window.border-body.mt-2
        .row
          .col-4
            = link_to user_path(@item.user_id) do
              = image_tag @item.user.avatar(:thumb), class: 'border'
          .col-8
            = link_to user_path(@item.user_id) do
              %p.font-weight-bold= "#{@item.user.second_name} #{@item.user.first_name}"
            %p= "#{t(:ads)}: #{@item.user.items.count}"
            = link_to user_path(@item.user_id) do
              %p.user-registered.text-right= "#{t(:registered_at)}: #{@item.user.created_at.strftime("%B %d, %Y")}"
  .row
    .col-8.mt-2
      %h4.font-weight-bold.text-center= "#{t(:about)} #{@item.title}"
  %p
    %b Title:
    = @item.title
  %p
    %b Category:
    = @item.category
  %p
    %b Manufacturer:
    = @item.manufacturer
  %p
    %b Condition:
    = @item.condition
  .row
    .col-8.mt-2
      %h4.font-weight-bold.text-center= t(:description)
      %h5= @item.description
  - if policy(@item).update?
    = link_to t(:edit), edit_item_path(@item), class: 'btn btn-primary'
  = link_to t(:back), items_path, class: 'btn btn-secondary'
  - if policy(@item).destroy?
    = link_to t(:destroy), item_path(@item), class: 'btn btn-danger', method: :delete, data: { confirm: t(:not_sure) }