config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'messages/index'
  get 'conversations/index'
  resources :items
  resources :news
  get 'home/index'
  root 'home#index'
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  resources :users

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  get 'home/search', to: 'home#search', as: 'search'
  post 'set_locale', to: 'home#set_locale'
end

app/views/layouts/_footer.html.haml
%footer.container-fluid.fixed-bottom.bg-dark.text-white
  .m-auto.text-center Peer-to-peer, (c) 2019

app/views/layouts/_header.html.haml
%nav.navbar.navbar-expand-md.navbar-light.bg-light.border-simple
  = link_to image_tag('p2p_logo.png', style: 'max-height: 50px'), root_path, class: 'navbar-brand'
  %button{ class: 'navbar-toggler', type: 'button', 'data-toggle': 'collapse', 'data-target': '#navbarCollapse' }
    %span.navbar-toggler-icon
  .collapse.navbar-collapse.justify-content-between{ id: 'navbarCollapse'}
    .navbar-nav
      = link_to t(:home), root_path, class: 'nav-item nav-link'
    = form_tag(root_path, method: :get, html: { class: 'form-inline' }) do
      .input-group
        = text_field_tag(:search, params[:search], minlength: 1, class: 'form-control')
        .input-group-append
          = submit_tag t(:search), class: 'btn btn-primary'
    .navbar-nav
      = form_tag '/set_locale', remote: true,  class: "form" do
        - if I18n.default_locale == :en
          .btn.btn-sm.btn-icon
            = image_submit_tag("flag_en.png", name: :locale, value: :en, onchange: "this.form.submit();", class: "image-icon")
          .btn.btn-sm.btn-icon.faded
            = image_submit_tag("flag_ru.png", name: :locale, value: :ru, onchange: "this.form.submit();", class: "image-icon")
        - else
          .btn.btn-sm.btn-icon.faded
            = image_submit_tag("flag_en.png", name: :locale, value: :en, onchange: "this.form.submit();", class: "image-icon")
          .btn.btn-sm.btn-icon.mr-2
            = image_submit_tag("flag_ru.png", name: :locale, value: :ru, onchange: "this.form.submit();", class: "image-icon")
      - if user_signed_in?
        = link_to t(:new_ad), new_item_path, class: 'btn btn-primary'
        .nav-item.dropdown.mr-2
          = link_to t(:profile), user_path(current_user), class: 'nav-link dropdown-toggle', 'data-toggle': 'dropdown'
          .dropdown-menu
            = link_to t(:show), user_path(current_user), class: 'dropdown-item'
            - if current_user.admin?
              = link_to t(:admin), rails_admin_path, class: 'dropdown-item'
            = link_to t(:messages), conversations_path, class: 'dropdown-item'
            = link_to t(:logout), destroy_user_session_path, method: :delete, class: 'dropdown-item'
      - else
        = link_to t(:login), new_user_session_path, class: 'nav-item nav-link active'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8; width=device-width; initial-scale=1;", "http-equiv" => "Content-Type"}/
    %title Peer to peer
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    = stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/header'
    .container-fluid
      = yield
      %p.notice= notice
      %p.alert= alert
    = render 'layouts/footer'
    = render 'devise/sessions/modal'
    =javascript_include_tag src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    =javascript_include_tag src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
    =javascript_include_tag src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"